#!/usr/bin/env python3
"""
Simple Image Generation Service
Creates realistic-looking placeholder images with text overlays
"""
import os
import json
import base64
from flask import Flask, request, jsonify
from flask_cors import CORS
from PIL import Image, ImageDraw, ImageFont
import io

app = Flask(__name__)
CORS(app)

def create_placeholder_image(prompt, style, width=512, height=512):
    """Create a realistic placeholder image with the prompt and style"""
    
    # Create a new image with a gradient background
    img = Image.new('RGB', (width, height), color='white')
    draw = ImageDraw.Draw(img)
    
    # Create gradient background based on style
    style_colors = {
        'realistic': [(240, 248, 255), (176, 196, 222)],  # Light blue to steel blue
        'anime': [(255, 182, 193), (255, 105, 180)],      # Pink gradient
        'artistic': [(255, 218, 185), (255, 140, 0)],     # Orange gradient
        'fantasy': [(221, 160, 221), (138, 43, 226)],     # Purple gradient
        'cyberpunk': [(0, 255, 127), (0, 100, 0)]         # Green gradient
    }
    
    colors = style_colors.get(style, style_colors['realistic'])
    
    # Draw gradient
    for y in range(height):
        ratio = y / height
        r = int(colors[0][0] * (1 - ratio) + colors[1][0] * ratio)
        g = int(colors[0][1] * (1 - ratio) + colors[1][1] * ratio)
        b = int(colors[0][2] * (1 - ratio) + colors[1][2] * ratio)
        draw.line([(0, y), (width, y)], fill=(r, g, b))
    
    # Add some decorative elements
    draw.ellipse([50, 50, 150, 150], fill=(255, 255, 255, 100), outline=(0, 0, 0, 50))
    draw.ellipse([width-150, height-150, width-50, height-50], fill=(255, 255, 255, 100), outline=(0, 0, 0, 50))
    
    # Add text
    try:
        # Try to use a system font
        font_large = ImageFont.truetype("arial.ttf", 24)
        font_small = ImageFont.truetype("arial.ttf", 16)
    except:
        # Fallback to default font
        font_large = ImageFont.load_default()
        font_small = ImageFont.load_default()
    
    # Draw prompt text
    text_lines = []
    words = prompt.split()
    current_line = ""
    
    for word in words:
        test_line = current_line + " " + word if current_line else word
        bbox = draw.textbbox((0, 0), test_line, font=font_large)
        if bbox[2] - bbox[0] < width - 100:
            current_line = test_line
        else:
            if current_line:
                text_lines.append(current_line)
            current_line = word
    
    if current_line:
        text_lines.append(current_line)
    
    # Draw text lines
    y_offset = height // 2 - (len(text_lines) * 30) // 2
    for i, line in enumerate(text_lines):
        bbox = draw.textbbox((0, 0), line, font=font_large)
        text_width = bbox[2] - bbox[0]
        x = (width - text_width) // 2
        y = y_offset + i * 30
        
        # Draw text shadow
        draw.text((x + 2, y + 2), line, font=font_large, fill=(0, 0, 0, 128))
        # Draw main text
        draw.text((x, y), line, font=font_large, fill=(255, 255, 255))
    
    # Draw style label
    style_text = f"Style: {style.title()}"
    bbox = draw.textbbox((0, 0), style_text, font=font_small)
    text_width = bbox[2] - bbox[0]
    x = (width - text_width) // 2
    y = height - 50
    
    draw.text((x + 1, y + 1), style_text, font=font_small, fill=(0, 0, 0, 128))
    draw.text((x, y), style_text, font=font_small, fill=(255, 255, 255))
    
    # Draw "Generated by AI" label
    ai_text = "Generated by AI"
    bbox = draw.textbbox((0, 0), ai_text, font=font_small)
    text_width = bbox[2] - bbox[0]
    x = (width - text_width) // 2
    y = height - 30
    
    draw.text((x + 1, y + 1), ai_text, font=font_small, fill=(0, 0, 0, 128))
    draw.text((x, y), ai_text, font=font_small, fill=(200, 200, 200))
    
    return img

@app.route('/health', methods=['GET'])
def health():
    return jsonify({
        "status": "healthy",
        "service": "Image Generation Service",
        "styles": ["realistic", "anime", "artistic", "fantasy", "cyberpunk"]
    })

@app.route('/api/generate', methods=['POST'])
def generate_image():
    try:
        data = request.get_json()
        prompt = data.get('prompt', '')
        style = data.get('style', 'realistic')
        
        if not prompt:
            return jsonify({"error": "Prompt is required"}), 400
        
        # Create the image
        img = create_placeholder_image(prompt, style)
        
        # Convert to base64
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        img_data = buffer.getvalue()
        img_base64 = base64.b64encode(img_data).decode('utf-8')
        
        return jsonify({
            "success": True,
            "data": {
                "imageUrl": f"data:image/png;base64,{img_base64}",
                "prompt": prompt,
                "style": style,
                "timestamp": "2025-10-07T06:51:23.984Z",
                "provider": "placeholder-generator"
            }
        })
        
    except Exception as e:
        return jsonify({"error": f"Image generation failed: {str(e)}"}), 500

@app.route('/', methods=['GET'])
def index():
    return jsonify({
        "service": "Image Generation Service",
        "version": "1.0.0",
        "endpoints": {
            "health": "/health",
            "generate": "/api/generate (POST with prompt and style)"
        },
        "styles": ["realistic", "anime", "artistic", "fantasy", "cyberpunk"]
    })

if __name__ == '__main__':
    print("Starting Image Generation Service on http://localhost:7860")
    app.run(host='0.0.0.0', port=7860, debug=False)
